### ISSUE TITLE
Please add support for m4b files

### ISSUE THREAD

**Issue by Emasoft** [Josef-Friedrich/phrydy#1]
Please add support for m4b files. I have many files of such type in my audio collection. Some are audiobooks, some other are mixed music tracks and audiobooks.

**Comment by Josef-Friedrich** [comment]
Since I don't own a m4b file, I only tried a single test file:

https://software-download.name/sample-m4b-audio-file/dl/m4b-sample-audio.zip

```
#! /usr/bin/env python

from phrydy import MediaFileExtended
f = MediaFileExtended('m4b.m4b')

for key in MediaFileExtended.readable_fields():
    value = getattr(f, key)
    if key != 'art' and value:
        print('{}: {}'.format(key, value))
```

```
title: Chapter 5
artist: American Standard Version
album: The General Epistle of James
genres: ['Speech']
genre: Speech
track: 5
comments: www.librivox.org
albumartist: American Standard Version
encoder: Nero AAC codec / May 26 2006
date: 2007-01-01
year: 2007
length: 211.28562358276645
samplerate: 44100
bitdepth: 16
bitrate: 16923
channels: 2
format: AAC
```

I think m4b files are supported.

Since phrydy is a wrapper around mediafile and mediafile is a wrapper around mutagen and mutagen supports m4b files, phrydy should also support m4b files.

My renaming tool renames the file also:

```
audiorenamer --extension m4b m4b.m4b
```
